//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Icon
    {
        public const string BundleName = "icon";
        public const string ACHIEVEMENT = "achievement";
        public const string ACHIEVEMENT_ALL_ICON = "achievement_all_icon";
        public const string ACHIEVEMENT_TIME_ICON = "achievement_time_icon";
        public const string BALL_ICON = "ball_icon";
        public const string BOMB_ICON = "bomb_icon";
        public const string COLLECTABLE_ICON = "collectable_icon";
        public const string CRITICAL_ICON = "critical_icon";
        public const string DAMAGE_ICON = "damage_icon";
        public const string EXP_ICON = "exp_icon";
        public const string FLY_ICON = "fly_icon";
        public const string MOVEMENT_ICON = "movement_icon";
        public const string PAIRED_BALL_ICON = "paired_ball_icon";
        public const string PAIRED_BOMB_ICON = "paired_bomb_icon";
        public const string PAIRED_ROTATE_SWORD_ICON = "paired_rotate_sword_icon";
        public const string PAIRED_SIMPLE_KNIFE_ICON = "paired_simple_knife_icon";
        public const string PAIRED_SIMPLE_SWORD_ICON = "paired_simple_sword_icon";
        public const string ROTATE_SWORD_ICON = "rotate_sword_icon";
        public const string SIMPLE_KNIFE_ICON = "simple_knife_icon";
        public const string SIMPLE_SWORD_ICON = "simple_sword_icon";
    }
    public class Sound
    {
        public const string BundleName = "sound";
        public const string ABILITYLEVELUP = "AbilityLevelUp";
        public const string BALL = "Ball";
        public const string BOMB = "Bomb";
        public const string DIE = "Die";
        public const string ENEMYDIE = "EnemyDie";
        public const string EXP = "Exp";
        public const string GAMEPASS = "GamePass";
        public const string GETALLEXP = "GetAllExp";
        public const string GOLD = "Gold";
        public const string HIT = "Hit";
        public const string HPITEM = "HpItem";
        public const string HURT = "Hurt";
        public const string KNIFE = "Knife";
        public const string LEVELUP = "LevelUp";
        public const string TREASURECHEST = "TreasureChest";
        public const string WALK = "Walk";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
